### ISSUE TITLE
urllib3 module deprecation warning

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/stix-shifter#1131]
**Describe the bug**
Get a warning message when using stix-shifter. The module `urllib3.contrib.pyopenssl` used by both `requests_toolbelt` and `botocore` is deprecated and will be removed in a future release.

https://github.com/urllib3/urllib3/issues/2680

**To Reproduce**
1. install the latest stix-shifter 4.3.1
2. run stix-shifter

**Expected behavior**
no warning

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Python 3.10

**Additional context**
```
  /usr/lib64/python3.10/site-packages/requests_toolbelt/_compat.py:56: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
    from requests.packages.urllib3.contrib.pyopenssl \

  /usr/lib64/python3.10/site-packages/botocore/httpsession.py:41: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
```

**Comment by DerekRushton** [comment]
I suspect that this has already been fixed. Due to the age, I am going to close this item, however feel free to reopen it if this is still an issue.
