### ISSUE TITLE
Cybereason connector fails pattern translation on multiple STIX observations

### ISSUE THREAD

**Issue by delliott90** [opencybersecurityalliance/stix-shifter#1215]
**Describe the bug**
Trying to translate a STIX pattern with more than one observations fails. I also noticed that I'll get an operator not supported error when using OR between observations even though stix-shifter should be treating both OR and AND operators between the observations as OR since stix-shifter doesn't have the context to know if all observations in a pattern are coming from the same event.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the translation command `python main.py translate cybereason query '{}' "[network-traffic:src_ref.value = '127.0.0.1' AND url:value = 'example.com'] AND [process:pid = 1234]"`
2. See the error
```
 2022-11-28 11:53:42,810 stix_shifter.stix_translation.stix_translation ERROR    Caught exception: Link is not found between elements <class 'stix_shifter_modules.cybereason.stix_translation.query_constructor.LinkNotFoundException'>
 2022-11-28 11:53:42,810 stix_shifter_utils.stix_translation.stix_translation_error_mapper ERROR    received exception => LinkNotFoundException: Link is not found between elements
{
    "success": false,
    "connector": "cybereason",
    "code": "invalid_parameter",
    "error": "cybereason connector error => Error when converting STIX pattern to data source query: Link is not found between elements"
}
```

**Expected behavior**
Translation should give one or more native Cybereason queries

**Comment by thangaraj-ramesh** [comment]
PR #1224 - Updated to address this issue.

**Comment by delliott90** [comment]
PR listed above clarifies the limitations of this connector when using the AND operator between unlinked properties.
