### ISSUE TITLE
Async lib aiogoogle for gcp_chronicle connector

### ISSUE THREAD

**Issue by baulus** [opencybersecurityalliance/stix-shifter#1220]
**Describe the feature**
Async change requires all connectors to make async calls to their APIs. gcp_chronicle connector is still using sync lib google-api-python-client

**Solution**
Consider using https://pypi.org/project/aiogoogle/ async lib for gcp_chronicle

**Comment by DerekRushton** [comment]
This looks like it's already done. I'm going to mark it as closed due to the age of this item.
