### ISSUE TITLE
splunk connector does not properly format MAC addresses

### ISSUE THREAD

**Issue by pcoccoli** [opencybersecurityalliance/stix-shifter#1238]
**Describe the bug**
I've seen examples of MACs coming back with dashes, e.g. `01-02-03-04-05-06` instead of `01:02:03:04:05:06`

**To Reproduce**
1. python main.py execute splunk splunk ... (can't share creds and the search, etc.)

**Expected behavior**
> The MAC address value MUST be represented as a single colon-delimited, lowercase MAC-48 address, which MUST include leading zeros for each octet.
> Example: `00:00:ab:cd:ef:01`
From https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_f92nr9plf58y

Version cfaaf4fb086963d58899f43f75479f83864bb5e2 (develop branch post 4.5.2)

**Comment by thangaraj-ramesh** [comment]
we have fixed the MAC address format issue and raised the PR. Please review the below PR : https://github.com/opencybersecurityalliance/stix-shifter/pull/1386

**Comment by delliott90** [comment]
Fixed with https://github.com/opencybersecurityalliance/stix-shifter/pull/1386
