### ISSUE TITLE
Stix 2.1 Upgrade

### ISSUE THREAD

**Issue by brettforbes** [opencybersecurityalliance/stix-shifter#1247]
Hi,

Stix 2.1 is the current version, and we believe there is a new version planned. There are some differences between v2 and v2.1.

Is there a plan to upgrade Stix-Shifter to Stix 2.1 and does it take into account the new version coming on?

Please advise, thanks

**Comment by priamai** [comment]
This would be great please!

**Comment by brettforbes** [comment]
We note in terms of the Stix Best Practice document that we are meant to unpack v2.0 Cyber Observable Containers into v2.1 Cyber Observable Objects. Thus if we integrate with your software, we could do this for you.But perhaps it is best for us to find out your upgrade pathway first.
https://docs.oasis-open.org/cti/stix-bp/v1.0.0/cn01/stix-bp-v1.0.0-cn01.html#_Toc111555295

**Comment by pcoccoli** [comment]
I think this is implemented already.  E.g. https://github.com/opencybersecurityalliance/stix-shifter/blob/master/OVERVIEW.md#translating-results-into-stix-21

**Comment by brettforbes** [comment]
excellent, thank you
