### ISSUE TITLE
stix-shifter return records have limited size

### ISSUE THREAD

**Issue by tingdai** [opencybersecurityalliance/stix-shifter#1285]
**Describe the bug**
- When executing a query that requires more than 10k returns, stix-shifter failed with RuntimeError.

**To Reproduce**
- Use stix-shift to execute a query and specify the result limit more than 10000, e.g., `--results 11000`. An example command shows as follows:
```
stix-shifter execute elastic_ecs elastic_ecs '{"type":"identity","id":"xxx","name":"elastic","identity_class":"events"}' '{"host":"xxx", "port":xxx, "selfSignedCert": false}' '{"auth":{"id": "xxx", "api_key":"yyy"}}' "[ipv4-addr:value = '127.0.0.1'] START t'2021-10-17T12:00:00Z' STOP t'2022-10-18T00:00:00Z'" --results 11000
```

**Expected behavior**
On ElasticSearch side, the page limit is set as 10k by default, when stix-shifter wants to retrieve more than 10k data using simple [GET API](https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/stix_shifter_modules/elastic_ecs/stix_transmission/api_client.py#L55), RuntimeError happens. 

**Additional context**
As I[ssue 143](https://github.com/opencybersecurityalliance/kestrel-lang/issues/143) listed, we need to use advanced paging API to transmit results between stix-shifter and ElasticSearch.

**Comment by tingdai** [comment]
For large queries, we can use [search_after](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html) API as suggested.
However, there are some challenges that need to addressed:
1. We cannot use indices (plural) for point in time ([PIT](https://www.elastic.co/guide/en/elasticsearch/reference/current/point-in-time-api.html)). This is because `search_after` does not support it. For example, if we use the following APIs: 
```
POST winlogbeat-*/_pit?keep_alive=2m

GET winlogbeat-*/_search?size=10&from=0
{
  "query": {
    "query_string": {
      "query": "xxxxx"
    }
  },
  "pit": {
    "id": "xxxxx",  ### the id is provided by the previous POST api
    "keep_alive" : "2m"
  },
  "sort": [
    {"@timestamp": "asc"}
  ]
}
```
we will  get validation failures:
```
Validation Failed: 1: [indices] cannot be used with point in time. Do not specify any index with point in time.;
```
This will not be an issue in threat hunting, as @subbyte said users always retrieve old data, thus a snapshot is not necessary. Our solution would be to exclude `pit` in `search_after` API.

**Comment by tingdai** [comment]
2. To use `search_after`, we have to use `sort` API to break the tie and give us the last item from the previous retrieval. Currently, `@timestamp` is a good solution:
```
GET winlogbeat-*/_search
{
  "_source": {
    "includes": ["@timestamp", "source.*", "destination.*", "event.*", "client.*", "server.*", "host.*","network.*", "process.*", "user.*", "file.*", "url.*", "registry.*", "dns.*", "tags"]
  },
  "query": {
    "query_string": {
      "query": "(source.ip : \"127.0.0.1\" OR destination.ip : \"127.0.0.1\" OR client.ip : \"127.0.0.1\" OR server.ip : \"127.0.0.1\" OR host.ip : \"127.0.0.1\" OR dns.resolved_ip : \"127.0.0.1\") AND (@timestamp:[\"2021-10-17T12:00:00.000Z\" TO \"2022-10-18T00:00:00.000Z\"])"
    }
  },
  "sort": [
    {"@timestamp": "asc"}
  ]
}
```
The last item's timestamp is 1635133626942, we just put 1635133626942 in the next query's `search_after` field.
```
GET winlogbeat-*/_search
{
  "_source": {
    "includes": ["@timestamp", "source.*", "destination.*", "event.*", "client.*", "server.*", "host.*","network.*", "process.*", "user.*", "file.*", "url.*", "registry.*", "dns.*", "tags"]
  },
  "query": {
    "query_string": {
      "query": "(source.ip : \"127.0.0.1\" OR destination.ip : \"127.0.0.1\" OR client.ip : \"127.0.0.1\" OR server.ip : \"127.0.0.1\" OR host.ip : \"127.0.0.1\" OR dns.resolved_ip : \"127.0.0.1\") AND (@timestamp:[\"2021-10-17T12:00:00.000Z\" TO \"2022-10-18T00:00:00.000Z\"])"
    }
  },
  "sort": [
    {"@timestamp": "asc"}
  ],
  "search_after": [                                
    1635133626942
  ]
}
```

**Comment by tingdai** [comment]
3. [`search_after`](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html) do not use `size`(length) and `from`(offset) fields, because they are problematic:

> Avoid using from and size to page too deeply or request too many results at once. Search requests usually span multiple shards. Each shard must load its requested hits and the hits for any previous pages into memory. For deep pages or large sets of results, these operations can significantly increase memory and CPU usage, resulting in degraded performance or node failures.
> By default, you cannot use from and size to page through more than 10,000 hits. This limit is a safeguard set by the [index.max_result_window](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-max-result-window) index setting. If you need to page through more than 10,000 hits, use the [search_after](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after) parameter instead.

Thus, we should not use `offset` and `size` in stix-shifter transmission [`result()`](https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/stix_shifter/stix_transmission/stix_transmission.py#L56) function for elasticsearch when we are using `search_after` pagination.
We should ignore those parameters when we conduct a deep pagination search. Maybe assign them with negative values to differentiate them from simple searches.

**Comment by tingdai** [comment]
4. We should support batch queries but hide the batch size from users or Kestrel side, especially avoid using `RETRIEVAL_BATCH_SIZE`  and `result_retrieval_offset` in Kestrel when conducting pagination search.
In [Kestrel](https://github.com/opencybersecurityalliance/kestrel-lang/blob/develop/src/kestrel_datasource_stixshifter/interface.py#L208) with the following loop:
```
                    while has_remaining_results:
                        result_batch = transmission.results(
                            search_id, result_retrieval_offset, RETRIEVAL_BATCH_SIZE
                        )
                        if result_batch["success"]:
                            new_entries = result_batch["data"]
                            if new_entries:
                                connector_results += new_entries
                                result_retrieval_offset += RETRIEVAL_BATCH_SIZE
                                if len(new_entries) < RETRIEVAL_BATCH_SIZE:
                                    has_remaining_results = False
                            else:
                                has_remaining_results = False
```
If a user wants to retrieve 10k data, he/she could use only one `search` API with only one connection to elasticsearch to get a whole page, suppose that the [`index.max_result_window`](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-max-result-window) is 10k. 
However, using the above batch loop, the `RETRIEVAL_BATCH_SIZE` is defined as 512, the user has to consume 10k/512=20 connections. It is too expensive.

**Comment by subbyte** [comment]
Thanks, Ting! Some questions to further understand the situation:

1. There are two Elastic APIs that provide results more than a page:
- search_after
- scroll

PIT is not a concern for us. Could you compare the two APIs without the PIT aspect to see whether the scroll API is a better fit? And why it is not recommended over search_after in the doc?

2. `tie_breaker_id` is used in the [examples](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html). Is it a field in the index or a field generated on the fly when searching? If a static field, Does ECS (Elastic Common Schema) has it or similar field to be used for the same purpose (check data on our testing server)?

3. This example in the elastic doc uses `search_after` but does not have `size` parameter, if there are more than 10k (a page) results after `[1463538857, "654323"]`, will it give the same page limit error?
```
GET twitter/_search
{
    "query": {
        "match": {
            "title": "elasticsearch"
        }
    },
    "search_after": [1463538857, "654323"],
    "sort": [
        {"date": "asc"},
        {"tie_breaker_id": "asc"}
    ]
}
```

4. Elastic has its native Python client (https://elasticsearch-py.readthedocs.io/). Is there any difference between the native Python client and the direct REST API interface? Check whether the current `elastic_ecs` is using the direct REST API interface and whether there is any advantage using the native Python client.

**Comment by tingdai** [comment]
TODO: change implementation in https://github.com/opencybersecurityalliance/stix-shifter/pull/1299 
- Move the while loop from the stix-shifter [connector](https://github.com/opencybersecurityalliance/stix-shifter/blob/1e89e283be2134a5d417301e0f872d4c63eb0f63/stix_shifter_modules/elastic_ecs/stix_transmission/connector.py#L84-L101) to Kestrel. As @pcoccoli suggested, extract all query data and stored in memory by stix-shifter is impractical. Kestrel should iterate the paginations and in each iteration, Kestrel gets one page of data and store them in DB.
- Use the `metadata` field in [`create_results_stix_connection`](https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/stix_shifter/stix_transmission/stix_transmission.py#L62) to pass the `search_after` values. One example as @delliott90 pointed out is [`ibm_security_verifier`](https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/stix_shifter_modules/ibm_security_verify/stix_transmission/api_client.py#L168).

**Comment by tingdai** [comment]
Two potential approaches to handle `offset` and `metadata` arguments:
- Kestel uses .....
- stix-shifter transmission instance keep stateful to decide `metadata` be `None` in the first page and be `lastsortvalue` in the following pages.

**Comment by subbyte** [comment]
I am trying to add a view from upper layer usage to understand the two approaches @tingdai will describe in details:
1. The upper layer needs to read `lastsortvalue` from last query results and passes it to the next query if the value exists.
2. The upper layer needs to change nothing on current while loop, but needs to ensure using the same Python object/instance of the `stix_shifter.stix_translation`, so the instance will keep the `lastsortvalue` internally to add to the next query call.

In either way, the upper layer while loop computes the offset as usual (last offset + len(return)) and uses it in the query call as usual. It is not aware this value is actually not used by the connector when `lastsortvalue` exists.

The only place for a search_after-supported connector to be queried without `lastsortvalue` is the first call of query, where the offset is expected to be 0 (same as `lastsortvalue` is before the first result). For such a connector, e.g., `elastic_ecs`, it may needs to have logic in case the upper layer uses offset but not `lastsortvalue` (maybe support it with simple API, or give a warning). This is the downside of the first approach, while the second approach handles `lastsortvalue` inside stix-shifter, so it will ignore the offset, and largely does not need simple API implementation besides search_after (unless an upper layer make the first call with `offset!=0`), or want to do a query again (same offset) it did before (it actually can't since the stix-shifter internal state changes).

**Comment by tingdai** [comment]
- Stix-shifter: Expose get_pagesize() API in stix-shifter transmisson module and support pagination using lastsortvalue/metadata in 8af9893983e14072d20fc4432ab823badfd886e1
- Kestrel: use pagesize/max_result_window as `retrieval_batch_size`, and extract `lastsort` as `metadata` to support search_after in ElasticSearch https://github.com/opencybersecurityalliance/kestrel-lang/pull/287/commits

**Comment by tingdai** [comment]
This issue is addressed in https://github.com/opencybersecurityalliance/stix-shifter/pull/1299/
