### ISSUE TITLE
stix-shifter release procedure

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/stix-shifter#1296]
**Describe the bug**
Today on pypi the latest version of stix-shifter is 5.0.0, but this version hasn't been released (github repo release section) yet. And there are issues with this version.

Two things:
1. there is an error as described below.
2. we may need a mechanism in CI/CD to set such version (5.0.0) as pre-release in pypi so `pip install stix-shifter` will not install it as the latest version. One can install it with `--pre` (https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-pre)

**To Reproduce**
```
$ python3 -m venv venv/test2
$ . ./venv/test2/bin/activate
$ pip install -U pip setuptools wheel
$ pip install stix-shifter stix-shifter-utils stix-shifter-modules-elastic-ecs
$ stix-shifter execute elastic_ecs elastic_ecs '{"type":"identity","id":"identity--f431f809-377b-45e0-aa1c-6a4751cae5ff","name":"elastic","identity_class":"events"}' '{"host":"elastic_server_url", "port":9200, "selfSignedCert": false}' '{"auth":{"id": "xxx", "api_key":"yyy"}}' "[ipv4-addr:value = '127.0.0.1'] START t'2021-10-17T12:00:00Z' STOP t'2022-10-18T00:00:00Z'" --results 11000
```

Get error:
```
 2023-01-25 14:06:58,246 stix_shifter_utils.stix_transmission.utils.RestApiClientAsync ERROR    exception occured during requesting url: Cannot serialize non-str key b'ApiKey xxxyyyzzz==' <class 'TypeError'>
 2023-01-25 14:06:58,247 stix_shifter_utils.utils.error_response ERROR    error occurred: Cannot serialize non-str key b'ApiKey xxxyyyzzz=='
```

**Expected behavior**
run without error

**Comment by DerekRushton** [comment]
I'm going to close this. We are on version 7.0.11 at the moment and I'm not sure if this is still applicable. If it's still an issue, we can reopen this.
