### ISSUE TITLE
Add metadata argument and docuemantion for CLI

### ISSUE THREAD

**Issue by mdazam1942** [opencybersecurityalliance/stix-shifter#1365]
**Is your feature request related to a problem? Please describe.**
A new parameter named metadata has been added to stix-shifter results and status transmission call: https://github.com/opencybersecurityalliance/stix-shifter/blob/8b7e00a8e5d4f6613034583b04e0d3cf8d8e58b1/stix_shifter/stix_transmission/stix_transmission.py#L56

This parameter basically can be used to pass additional information for the connector to make api calls to the datasource. For example: next page token for pagination.

Currently it can only be used in the client script. CLI doesn't understand this new parameter.

**Describe the solution you'd like**
We need to add that parameter as a CLI argument in the main stix-shifter script: https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/stix_shifter/scripts/stix_shifter.py

We also need to add usage documentation of this this metadata parameter.

**Comment by DerekRushton** [comment]
This appears to have been done. Closing this issue.
