### ISSUE TITLE
use f string instead of format string for better performance

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/stix-shifter#1379]
**Is your feature request related to a problem? Please describe.**
Editing the `api_client.py` for `elastic_ecs`, I find there are lots of format strings like:
```
endpoint = "{}?size={}".format(endpoint, length)
```

According to [this test](https://stackoverflow.com/a/38722192), f string can be 2-3 times faster than format string. May want to upgrade with f string.

**Comment by DerekRushton** [comment]
This is something we can address on a per connector basis and follow as a best practice. I am going to close this issue as I don't see us changing this across all of the connectors at once.
