### ISSUE TITLE
Azure Sentinel connector has wrong mapping for URL

### ISSUE THREAD

**Issue by delliott90** [opencybersecurityalliance/stix-shifter#1388]
**Describe the bug**
As seen here: https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/stix_shifter_modules/azure_sentinel/stix_translation/json/from_stix_map.json#L79
The mapping is for `url:name` when it should be `url:value`. Name is not a supported property of the URL object.

**Expected behavior**
The mapping should be for `url:value`

**Comment by pcoccoli** [comment]
https://github.com/opencybersecurityalliance/stix-shifter/blob/4b022cd972606274441fafc05699e22630361162/stix_shifter_modules/azure_sentinel/stix_translation/json/from_stix_map.json#L54
"binary_ref" must point to a `file`, and `file` does not have a `path` property.  It should be "binary_ref.parent_directory_ref.path".

https://github.com/opencybersecurityalliance/stix-shifter/blob/4b022cd972606274441fafc05699e22630361162/stix_shifter_modules/azure_sentinel/stix_translation/json/from_stix_map.json#L85
https://github.com/opencybersecurityalliance/stix-shifter/blob/4b022cd972606274441fafc05699e22630361162/stix_shifter_modules/azure_sentinel/stix_translation/json/to_stix_map.json#L471
Registry value fields are not an extension: https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_u7n4ndghs3qq
