### ISSUE TITLE
`elastic-ecs` mapping: create a `geo` SCO and make references from objects with geo attributes

### ISSUE THREAD

**Issue by Harmedox** [opencybersecurityalliance/stix-shifter#1409]
There is a [`Location`](https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_th8nitr8jb4k) SDO in STIX 2.1 that best represents geo-location attributes, but we cannot be referenced from Cyber-observable Objects. To solve this, a custom geo object is created, with references to it from other SCOs.

**Comment by brettforbes** [comment]
seems relatively straightforward, just make an extension to the location object with the geo code in it. This is generically useful, so if it is well thought through it can be submitted for approval
