### ISSUE TITLE
Validation of domain-name:value is extremely slow for certain invalid data

### ISSUE THREAD

**Issue by aidbutlr** [opencybersecurityalliance/stix-shifter#1528]
**Describe the bug**
The validation of domain-name:value properties can take up to 20 seconds to identify an invalid domain-name pattern.
The issue occurs here
https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/stix_shifter_utils/stix_translation/src/json_to_stix/json_to_stix_translator.py#L118
Using the regex from here
https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/stix_shifter_utils/stix_translation/src/json_to_stix/observable.py#L7

**To Reproduce**
1. With the following content mapped to domain-name:value column, the stix results translator will hang for 20 seconds.
 "a64a9282-0337-11e7-a6a5-00505680a503/934023ae-0339-11e7-a6a5-00505680a503"
2. To demonstrate the error independant of stix-shifter run the following

                
                import re
                
                domain_name =(r'^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(\.)?)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$')
                pattern = re.compile(domain_name)
                match = pattern.match
                stix_value="a64a9282-0337-11e7-a6a5-00505680a503/934023ae-0339-11e7-a6a5-00505680a503"
                print("Validating %s %s "%(stix_value,domain_name))
                if not match(str(stix_value)):
                    print("Not Valid")
                    exit()
                print("Valid")
                

**Expected behavior**
The validation should identify and remove the invalid content without hanging

**Comment by pcoccoli** [comment]
FWIW there's a third party `regex` module; if you `pip install regex` change `import re` to `import regex as re` it's much faster (around 160 µs on my laptop).

**Comment by mdazam1942** [comment]
`regex` module is significantly faster. we can go ahead just updating the module import to use the `regex` .
