### ISSUE TITLE
CrowdStrike connector error failing with a 400 code unless the search returns no records

### ISSUE THREAD

**Issue by frequent6198** [opencybersecurityalliance/stix-shifter#1548]
**Describe the bug**
Attempting to return records using the crowdstrike connector is causing a [worker: Transmitter-15:1] STIX-shifter transmission.result() error after upgrading to kestrel 1.7.x.   
There error in full:  

[ERROR] DataSourceError: [worker: Transmitter-15:1] STIX-shifter transmission.result() failed: crowdstrike connector error => {'success': False, 'connector': 'crowdstrike', 'error': "crowdstrike connector error => {'meta': {'query_time': 0.000673963, 'powered_by': 'legacy-detects', 'trace_id': 'db34db2e-0977-40cb-8901-9cfe8f28b67b'}, 'resources': [], 'errors': [{'code': 400, 'message': 'Validation error'}, {'code': 400, 'message': 'Validation error'}]}", 'code': 'unknown'}
please check data source config or test the query manually.  

**To Reproduce**  
1. Run a kestrel session using the crowdstrike connector. Make the query simple and something that will easily return results, and make sure it is a short time frame so that the first few queries do not return any results. 
2. Keep increasing the time range of the search in short amounts. Eventually, if there are any results, the query will hang until it fails with this error. 

e.g: 
```
test = GET process
       FROM stixshifter://source
       WHERE process:name != 'name'
       LAST 100 SECONDS
```
Block Executed in 2 seconds  
|VARIABLE | TYPE | #(ENTITIES) | #(RECORDS)|
-- | -- | -- | --|
|test | process | 0 | 0|
```
test = GET process
       FROM stixshifter://source
       WHERE process:name != 'name'
       LAST 1000 SECONDS
```
Block Executed in 2 seconds  
| VARIABLE | TYPE | #(ENTITIES) | #(RECORDS)|
|-- | -- | -- | --|
|test | process | 0 | 0|

```
test = GET process
       FROM stixshifter://source
       WHERE process:name != 'name'
       LAST 10000 SECONDS
```
Block Executed in 2 seconds  
| VARIABLE | TYPE | #(ENTITIES) | #(RECORDS)|
|-- | -- | -- | --|
|test | process | 0 | 0|
```
test = GET process
       FROM stixshifter://source
       WHERE process:name != 'name'
       LAST 10000 SECONDS
```
Block Executed in 2 seconds  
| VARIABLE | TYPE | #(ENTITIES) | #(RECORDS)|
|-- | -- | -- | --|
|test | process | 0 | 0|
```
test = GET process
       FROM stixshifter://source
       WHERE process:name != 'name'
       LAST 100000 SECONDS
```
Block Executed in 2 seconds  
| VARIABLE | TYPE | #(ENTITIES) | #(RECORDS)|
|-- | -- | -- | --|
|test | process | 0 | 0|  
```
test = GET process
       FROM stixshifter://source
       WHERE process:name != 'name'
       LAST 1000000 SECONDS
```
[ERROR] DataSourceError: [worker: Transmitter-15:1] STIX-shifter transmission.result() failed: crowdstrike connector error => {'success': False, 'connector': 'crowdstrike', 'error': "crowdstrike connector error => {'meta': {'query_time': 0.000673963, 'powered_by': 'legacy-detects', 'trace_id': 'db34db2e-0977-40cb-8901-9cfe8f28b67b'}, 'resources': [], 'errors': [{'code': 400, 'message': 'Validation error'}, {'code': 400, 'message': 'Validation error'}]}", 'code': 'unknown'}

**Expected behavior**
The query would not return an error. 

**Desktop (please complete the following information):**
 - AWS EC2 Ubuntu 20.04
 - Waterfox

**Comment by subbyte** [comment]
Thanks for reporting this @frequent6198 !

Could you update kestrel to 1.7.3 (`pip install -U kestrel-lang`) and then run the stix-shifter diagnosis tool (introduced in v1.7.3) and attached the results?
```
stix-shifter-diag source
```

**Comment by frequent6198** [comment]
#### Kestrel specific config
retrieval batch size: 2000
cool down after transmission: 0
enable fast translation: False

#### Config to be passed to stix-shifter
connector name: crowdstrike
connection object [ref: https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/OVERVIEW.md#connection]:
{
    "host": "api.crowdstrike.com",
    "port": 443,
    "options": {
        "result_limit": 4000,
        "timeout": 60
    }
}
configuration object [ref: https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/OVERVIEW.md#configuration]:
{
    "auth": {
        "client_id": "********",
        "client_secret": "********"
    }
}



## Diagnose: stix-shifter to data source connection (network, auth)

#### Results from stixshifter transmission.ping()
{
    "success": true
}



## Diagnose: stix-shifter query translation
Caught exception: Unable to map the following STIX Operators: [Like] to data source fields <class 'stix_shifter_utils.stix_translation.src.utils.exceptions.DataMappingException'>
received exception => DataMappingException: Unable to map the following STIX Operators: [Like] to data source fields
Traceback (most recent call last):
  File "/opt/tljh/user/bin/stix-shifter-diag", line 26, in <module>
    diag.diagnose_translate_query(patterns[0])
  File "/opt/tljh/user/lib/python3.9/site-packages/kestrel_datasource_stixshifter/diagnosis.py", line 87, in diagnose_translate_query
    dsl = translate_query(
  File "/opt/tljh/user/lib/python3.9/site-packages/kestrel_datasource_stixshifter/query.py", line 167, in translate_query
    raise DataSourceError(
kestrel.exceptions.DataSourceError: [ERROR] DataSourceError: STIX-shifter translation from STIX to native query failed with message: crowdstrike connector error => data mapping error : Unable to map the following STIX Operators: [Like] to data source fields
please check data source config or diagnose with stix-shifter-diag command.

**Comment by subbyte** [comment]
Interesting. It gives another error.

This new error might be caused by different versions of stix-shifter. Could you run any huntflow you had once, e.g.
```
test = GET process
       FROM stixshifter://source
       WHERE process:name != 'name'
       LAST 10000 SECONDS
```

And then use the diagnosis tool again to see if the error changes?

**Comment by frequent6198** [comment]
I achieved the same error after following those instructions. 

```
# Diagnose: config verification

#### Kestrel specific config
retrieval batch size: 2000
cool down after transmission: 0
enable fast translation: False

#### Config to be passed to stix-shifter
connector name: crowdstrike
connection object [ref: https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/OVERVIEW.md#connection]:
{
    "host": "api.crowdstrike.com",
    "port": 443,
    "options": {
        "result_limit": 4000,
        "timeout": 60
    }
}
configuration object [ref: https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/OVERVIEW.md#configuration]:
{
    "auth": {
        "client_id": "********",
        "client_secret": "********"
    }
}



## Diagnose: stix-shifter to data source connection (network, auth)

#### Results from stixshifter transmission.ping()
{
    "success": true
}



## Diagnose: stix-shifter query translation
Caught exception: Unable to map the following STIX Operators: [Like] to data source fields <class 'stix_shifter_utils.stix_translation.src.utils.exceptions.DataMappingException'>
received exception => DataMappingException: Unable to map the following STIX Operators: [Like] to data source fields
Traceback (most recent call last):
  File "/opt/tljh/user/bin/stix-shifter-diag", line 26, in <module>
    diag.diagnose_translate_query(patterns[0])
  File "/opt/tljh/user/lib/python3.9/site-packages/kestrel_datasource_stixshifter/diagnosis.py", line 87, in diagnose_translate_query
    dsl = translate_query(
  File "/opt/tljh/user/lib/python3.9/site-packages/kestrel_datasource_stixshifter/query.py", line 167, in translate_query
    raise DataSourceError(
kestrel.exceptions.DataSourceError: [ERROR] DataSourceError: STIX-shifter translation from STIX to native query failed with message: crowdstrike connector error => data mapping error : Unable to map the following STIX Operators: [Like] to data source fields
please check data source config or diagnose with stix-shifter-diag command.
```

**Comment by subbyte** [comment]
I think I get the reason why it gives another error. The first testing query I put in the diagnosis tool is `[ipv4-addr:value LIKE '%']`. However, `LIKE` is not supported in the CS connector currently, which is another issue besides the first issue you encountered.

Anyway, we now know your connection to the data source is valid (auth is good). While I will see if I get an walk around to avoid the second error in the diagnosis tool, someone else may help with the first error.

**Comment by mdazam1942** [comment]
Not really sure if it is a Crowdstrike connector issue. Connects queries the detection API. This is the readme of the connector: https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/stix_shifter_modules/crowdstrike/README.md

@frequent6198 Can you run results CLI commands directly in stix-shifter to verify?

**Comment by DerekRushton** [comment]
Given the lack reply, I am going to assume this issue is no longer valid. Reopen if this is still an issue.
