### ISSUE TITLE
Wrong Timestamp format in Sumologic Module

### ISSUE THREAD

**Issue by omarrdaniel** [opencybersecurityalliance/stix-shifter#1659]
**Describe the bug**
Docs: https://help.sumologic.com/docs/api/search-job/#create-a-search-job
The format used in the sumologic module is `YmdTHMS`. The right format (see docs) is `Y-m-dTH:M:S`

Also milliseconds not supported (.000Z)

When trying to execute the query with the wrong time format, I get this error: `"message" : "The 'from' field (null) contains an invalid time."`

**Comment by pcoccoli** [comment]
https://help.sumologic.com/docs/api/search-job/#request-parameters
Note that the docs also say "Can also be milliseconds since epoch".  I will create a PR shortly that uses this instead of ISO 8601, since stix-shifter support (at least) millisecond precision.
