### ISSUE TITLE
Carbon Black Response connector is improperly creating network-traffic objects.

### ISSUE THREAD

**Issue by pcoccoli** [opencybersecurityalliance/stix-shifter#198]
**Describe the bug**
It looks like it's creating a `network-traffic` object for every process using Cb's `interface_ip` as the source and `comms_ip` as the destination.  The end result is useless noise, or worse, misleading.  It looks like every process is opening a network connection.

I have an example Cb API response where a process has a `netconn_count` of 0 but the stix-shifted bundle still shows an `opened_connection_ref`.  That `network-traffic` object goes from `interface_ip` to `comms_ip`.

**To Reproduce**
1. use the connector/adapter thingy

**Expected behavior**
`network-traffic` objects should only be added if the process itself created them (i.e. `netconn_count` > 1).  I don't know the Cb API but `interface_ip` and `comms_ip` are not the right data values.

**Screenshots**
Can't share the data at this time.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by delliott90** [comment]
I also noticed that Carbon Black isn't adding protocols to the network traffic object which is a STIX requirement. The other adapters that create network traffic objects have the protocol come back in the data source results. This is reflected in the `to_stix_map`. I'm not sure how the protocol comes back from a Carbon Black query.
