### ISSUE TITLE
Domain name from QRadar not getting written to STIX object

### ISSUE THREAD

**Issue by delliott90** [opencybersecurityalliance/stix-shifter#222]
**Describe the bug**
If Qradar passes in a domain name without the `http://` or `https://`, a domain-name observed-data object will be written with an empty value. 

**To Reproduce**
1. Open a terminal to the stix-shifter root directory to use the CLI tools
2. Run `python main.py translate qradar results '{"type": "identity","id": "identity--f431f809-377b-45e0-aa1c-6a4751cae5ff","name": "QRadar","identity_class": "events"}' '[ { "domainname": "example.com" } ]'`
3. Note the resulting object:
```
"objects": {
    "0": {
        "type": "domain-name",
         "value": ""
   }
}
```

**Expected behavior**
The value should contain `"example.com"`

**Additional context**
If the QRadar results were `'[ { "domainname": "http://example.com" } ]'` then the STIX object's value would be `"http://example.com"` The issue is most likely in the `ToDomainName` transformer.

**Comment by mdazam1942** [comment]
I don't see this bug exists anymore. I ran few tests and found the domain object coming out fine. here's the test snapshot-
```
$ python main.py translate qradar results '{"type": "identity","id": "identity--f431f809-377b-45e0-aa1c-6a4751cae5ff","name": "QRadar","identity_class": "events"}' '[ { "domainname": "example.com" } ]' 

{ "type": "bundle", "id": "bundle--08d6c878-fa58-4f78-8047-794d6df896a7", "spec_version": "2.0", "objects": [ { "type": "identity", "id": "identity--f431f809-377b-45e0-aa1c-6a4751cae5ff", "name": "QRadar", "identity_class": "events" }, { "id": "observed-data--abc07c99-e2d0-4be5-a79e-43f5d76f3b67", "type": "observed-data", "created_by_ref": "identity--f431f809-377b-45e0-aa1c-6a4751cae5ff", "created": "2020-07-27T12:44:59.579Z", "modified": "2020-07-27T12:44:59.579Z", "objects": { "0": { "type": "domain-name", "value": "example.com" } }, "number_observed": 1 } ] }
```
