### ISSUE TITLE
Data type of `resolves_to_refs` property  for IP addresses and Domain name needs to be a list

### ISSUE THREAD

**Issue by mdazam1942** [opencybersecurityalliance/stix-shifter#223]
**Describe the bug**
Currently the data type of `resolves_to_refs` property  for IP addresses are setting as an integer or string value. But according to STIX 2.0 specification, it needs to be a list.

**To Reproduce**
1. Go to Open a terminal to the stix-shifter root directory to use the CLI tools
2. Translate a datasource result which contains both IPv4/IPv6 address and mac-address or Domain name
3. Note the resulting object:
```
"objects": {
                "0": {
                    "resolves_to_refs": "1",
                    "type": "ipv4-addr",
                    "value": "192.168.0.1"
                },
               "1": {
                    "type": "mac-addr",
                    "value": "AA:BB:CC:DD:11:22"
                }
}
```

**Expected behavior**
The resulting object should look like-

```
"objects": {
                "0": {
                    "resolves_to_refs":  ["1"],
                    "type": "ipv4-addr",
                    "value": "192.168.0.1"
                },
               "1": {
                    "type": "mac-addr",
                    "value": "AA:BB:CC:DD:11:22"
                }
}
```

**Comment by delliott90** [comment]
Resolved with https://github.com/opencybersecurityalliance/stix-shifter/pull/333
