### ISSUE TITLE
Inconsistency in API contract for translate function

### ISSUE THREAD

**Issue by JasonKeirstead** [opencybersecurityalliance/stix-shifter#234]
**Describe the bug**
There is an inconsistency in the API contract for the translate() function in STIX Translation module, because most translation modules return a list of queries, while the bundle module returns a single query string. This means the API does not have a solid contract and you have to check the type of the returned value in your code.

**To Reproduce**
dsl = translation.translate(query['translation_module'], 'query', self.identity_object, query['query'])

**Expected behavior**
All modules should return a list - if there is only one result it should be a single item list.

There should be a unit test that verifies the contract for modules

**Comment by delliott90** [comment]
This has been resolved in https://github.com/opencybersecurityalliance/stix-shifter/pull/236. All pattern translations, including STIX bundle, are returned in a list.
