### ISSUE TITLE
proxy host translate results issue

### ISSUE THREAD

**Issue by freunda** [opencybersecurityalliance/stix-shifter#288]
There is an unneeded json.dumps in translate_results in proxy_host.py. self.request_args["results"] is already a json

Run stix shifter in host mode, configure a proxy on cp4s, query data source using this host proxy. Results are malformed because of the unneeded json.dumps in translate_results in proxy_host.py

**Comment by delliott90** [comment]
Fixed in https://github.com/opencybersecurityalliance/stix-shifter/pull/1235
