### ISSUE TITLE
Webinar link results in "This site can't be reached" error

### ISSUE THREAD

**Issue by MitchellJThomas** [opencybersecurityalliance/stix-shifter#351]
**Describe the bug**
Clicking on webinar link not only takes a long time to load (which I realize will be different as per internet access)... but the result is a "This site can’t be reached".

**To Reproduce**
1. Click on https://ibm.biz/BdzTyA with a browser (I used Chrome)
2. Wait up to 4 minutes
3. See error "This site can’t be reached".

**Expected behavior**
A webinar video.

**Screenshots**
![Screen Shot 2020-06-12 at 10 27 56 AM](https://user-images.githubusercontent.com/2075623/84530190-93ec5680-ac97-11ea-8578-b35c2b6f292b.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: Version 83.0.4103.61 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
n/a

**Additional context**
None

**Comment by delliott90** [comment]
Closing, tested this in Chrome private tab and was unable to reproduce
