### ISSUE TITLE
Add missing fields to carbon black STIX-to-binary query mapping

### ISSUE THREAD

**Issue by delliott90** [opencybersecurityalliance/stix-shifter#355]
There are some fields defined in the CB Response API doc that aren't yet mapped. Some fields are represented in both process and binary queries, in which case the query defaults to binary (though I'm not sure why it was built that way).

There is an issue however with having patterns that mixes fields that are only represented in process or binary but not both. For example, if I have a pattern like  [process_observation OR binary_observation], I will get a translated query looking for both of the mapped fields in a binary query; I should instead get two queries, one for process and one for binary only looking for the fields relevant to each.

**Comment by mdazam1942** [comment]
mapping enhancement has been made in process mapping and we don't support binary mappings anymore
