### ISSUE TITLE
Using backslashes ("\") in STIX values with QRadar backend

### ISSUE THREAD

**Issue by barvhaim** [opencybersecurityalliance/stix-shifter#362]
I am trying to execute the following query for cp4s for QRadar 
`select * FROM events WHERE Image LIKE '%\powershell.exe%' limit 1000 START 1593407880000 STOP 1593451080000`

I added custom field at the STIX Shifter and connected to local QRadar, if running on QRadar I do get results, but cp4s won’t let me do the query as `[(process:image_ref.name LIKE '%\powershell.exe')] START t'2020-06-29T05:18:00.000Z' STOP t'2020-06-29T17:18:00.000Z'`, so it pass validation when adding extra \ to be `[(process:image_ref.name LIKE '%\\powershell.exe')] START t'2020-06-29T05:18:00.000Z' STOP t'2020-06-29T17:18:00.000Z'` but then, I don’t get any results since it query for `select * FROM events WHERE Image LIKE '%\\\\powershell.exe%' limit 1000 START 1593407880000 STOP 1593451080000` which does not match the single quote at the image name `%\powershell.exe%`

It worked fine only after adding un-escaping for the query before sending it to QRadar backend
`query = query.replace('\\\\', '\\')`

**Comment by mdazam1942** [comment]
this issue is resolved in [commit](https://github.com/opencybersecurityalliance/stix-shifter/pull/363/commits/8d65e78b17d4424d2bb23b18c453654fb18a5e65)
