### ISSUE TITLE
Failed to use "translate" from CLI when value includes backslashes (QRadar)

### ISSUE THREAD

**Issue by barvhaim** [opencybersecurityalliance/stix-shifter#364]
**Describe the bug**
Running `translate` command from CLI when value includes backslashes returns an error and failed to translate for QRadar AQL.

**To Reproduce**
1. Open terminal
2. Type: `python main.py translate qradar query "{}"  "[(x-ibm-ariel:event_name = 'event\\example')]" "{}"` which is valid STIX pattern for QRadar
3. Results in an error, however when using the same pattern through the Data Explorer it does work properly.

**Expected behavior**
AQL query: `... FROM events WHERE qidname = 'event\\example'`

**Screenshots**
<img width="921" alt="image" src="https://user-images.githubusercontent.com/16198896/86811037-278e2880-c086-11ea-8ea0-fbe44537fef6.png">
**Desktop (please complete the following information):**
 - OS: OSX terminal

**Comment by delliott90** [comment]
This may be fixed, will need to investigate.

**Comment by mdazam1942** [comment]
@barvhaim I think you need to escape both the backslashes to get `'event\\example'` in the query. -

`[(x-ibm-ariel:event_name = 'event\\\\example')]`

**Comment by barvhaim** [comment]
it works now with `\\` as-is, can close the issue,
`translate qradar query {} "[(windows-registry-key:key = 'HKLM\\SYSTEM'" {}`

`FROM events WHERE ObjectName = 'HKLM\\SYSTEM' limit 10000 last 5 minutes`
