### ISSUE TITLE
`ipv4-addr:value` with LIKE operator for QRadar is invalid query

### ISSUE THREAD

**Issue by barvhaim** [opencybersecurityalliance/stix-shifter#365]
**Describe the bug**
`ipv4-addr:value` with LIKE operator for QRadar is invalid query, for example this pattern `[ipv4-addr:value LIKE '127.%']` will translate to `...FROM events WHERE (sourceip LIKE '%127.%%' OR destinationip LIKE '%127.%%' OR identityip LIKE '%127.%%') limit 1000 last 5 minutes` which is invalid AQL query.

**To Reproduce**
1. Translate this STIX pattern to QRadar AQL: `[ipv4-addr:value LIKE '127.%']`
2. Paste the AQL into QRadar advanced search in Log Activity and see the syntax error

**Expected behavior**
Retrieve the events where IPv4 starts with 127.*
as this AQL will do:
`select * from events where str(sourceip) LIKE '127.%'`

**Screenshots**
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/16198896/86923782-28cb5e00-c137-11ea-8685-6cb1a136842a.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Comment by JasonKeirstead** [comment]
Should add a CAST() for the QRadar operator.

**Comment by mdazam1942** [comment]
this is fixed in commit#a398519b82b62954cf3a0084feb070b46a396060
