### ISSUE TITLE
[QRadar] Escaping `(` and `)` and `"` in value changes AQL meaning

### ISSUE THREAD

**Issue by barvhaim** [opencybersecurityalliance/stix-shifter#370]
**Describe the bug**

given the following STIX pattern: `[(process:command_line LIKE 'my command line is (here)')]`, when translating to AQL, the value is escaped and now is `LIKE '%my command line is \(here\)%'` which is different from `'my command line is (here)'` in QRadar.

the AQL `FROM events WHERE ProcessCommandLine LIKE '%my command line is \(here\)%' limit 1000 last 5 minutes` is different than `FROM events WHERE ProcessCommandLine LIKE '%my command line is (here)%' limit 1000 last 5 minutes` and will return zero results.

Using value as `LIKE '%my command line is (here)%'` does seems to be correct with QRadar, I think the escaping inside the value is not needed and changes the AQL.

**To Reproduce**
1. Generate the following event 
`<142>Jul 13 14:37:00 WIN-VM-BAR AgentDevice=WindowsLog	AgentLogFile=Microsoft-Windows-Sysmon/Operational	PluginVersion=7.2.9.105	Source=Microsoft-Windows-Sysmon	Computer=MSEDGEWIN10	OriginatingComputer=MSEDGEWIN10	User=SYSTEM	Domain=NT AUTHORITY	EventID=1	EventIDCode=1	EventType=1	EventCategory=1	RecordNumber=6257	TimeGenerated=1593692483	TimeWritten=1593692483	Level=Informational	Keywords=0x8000000000000000	Task=SysmonTask-SYSMON_CREATE_PROCESS	Opcode=Info Message=IntegrityLevel: System CommandLine: my command line is (here) CurrentDirectory: x Image: example\powershell.exe FileVersion: x ParentImage: C:\Windows\System32\svchost.exe ParentCommandLine: x`

2. Execute using STIX Shifter: `[(process:command_line LIKE 'my command line is (here)')]` you'll get zero results.
3. After removing from `query_constructor.py` line 88 to be `return '{}'.format(value.replace('\"', '\\"'))` and not `return '{}'.format(value.replace('\"', '\\"').replace('(', '\\(').replace(')', '\\)'))`, it will work fine

**Desktop (please complete the following information):**
 - QRadar 7.3.3 Community Edition

**Comment by barvhaim** [comment]
Update - Occur for LIKE clause where value has `"` sign as well, for example: 
`ProcessCommandLine LIKE '%% /C type nul > \"C:\Users\\%\Desktop\\%.exe%'` != `ProcessCommandLine LIKE '%% /C type nul > "C:\Users\\%\Desktop\\%.exe%'`

**Comment by delliott90** [comment]
@barvhaim Is this still an outstanding issue?

**Comment by barvhaim** [comment]
> @barvhaim Is this still an outstanding issue?
