### ISSUE TITLE
Invalid STIX bundles are able to be used with the Bundle connector, when it should reject them

### ISSUE THREAD

**Issue by JasonKeirstead** [opencybersecurityalliance/stix-shifter#376]
Currently the bundle connector allows an invalid bundle to be used, relying on an error to happen later on during filtering. It should validate the bundle in advance and reject any invalid bundle.

**Comment by mdazam1942** [comment]
we are doing the validation outside of the cp4s platform. we have included scripts and documentation that allows anyone to validate their stix bundle file. https://github.com/opencybersecurityalliance/stix-shifter/tree/develop/bundle_validator
