### ISSUE TITLE
Multiple values of `artifcat:payload_bin` translation for QRadar

### ISSUE THREAD

**Issue by barvhaim** [opencybersecurityalliance/stix-shifter#388]
QRadar module keywords (text in event payload) - STIX Shifter currently supports payload text search with "lucene" TEXT SEARCH. Some STIX patterns contains multiple "keywords", for example:

`"[artifact:payload_bin LIKE '%Set-ItemProperty%' AND(OR) artifact:payload_bin LIKE '%New-Item%']"`

which translated to:
`"FROM events WHERE TEXT SEARCH '%Set-ItemProperty%' AND(OR) TEXT SEARCH '%New-Item%'"`

and is invalid AQL, using "lucene" TEXT SEARCH should be like:
`TEXT SEARCH '%Set-ItemProperty% AND(OR) %New-Item%'`

Moreover, you also cannot use any other field in the WHERE clause when using TEXT SEARCH, for example: 
`[ipv4-addr:value = '127.0.0.1' AND artifact:payload_bin LIKE 'x']` will cause an invalid AQL 

Another way to make it work out-of-the-box is using `UTF8(payload) LIKE '...'` without "lucene".

**Comment by mdazam1942** [comment]
@barvhaim can you confirm 2nd part of the issue-
```
Moreover, you also cannot use any other field in the WHERE clause when using TEXT SEARCH, for example:
[ipv4-addr:value = '127.0.0.1' AND artifact:payload_bin LIKE 'x'] will cause an invalid AQL
```

I tried running this below aql query and its not complaining-

`SELECT * FROM events WHERE TEXT SEARCH 'x' AND (sourceip = '127.0.0.1' OR destinationip = '127.0.0.1' OR identityip = '127.0.0.1') limit 10000 last 5 minutes`

**Comment by mdazam1942** [comment]
ohk so I figured `TEXT SEARCH` operator needs to be the first otherwise aql throws error. this query fails-
`SELECT * FROM events WHERE (sourceip = '127.0.0.1' OR destinationip = '127.0.0.1' OR identityip = '127.0.0.1') AND TEXT SEARCH 'x' limit 10000 last 5 minutes`

so if you change the order of the object like this it will translate into a valid aql query-

`[ipv4-addr:value = '127.0.0.1' AND artifact:payload_bin LIKE 'x']`

**Comment by mdazam1942** [comment]
I'm confused.  I tried running the aql query which I thought is valid directly in QRadar console it works but api call fails.

**Comment by mdazam1942** [comment]
@barvhaim test it out with our current changes and let us know if that fixes the issue.
