### ISSUE TITLE
Documentation issue - reference to data_mapper.py

### ISSUE THREAD

**Issue by ejratl** [opencybersecurityalliance/stix-shifter#392]
**Describe the bug**
https://github.com/opencybersecurityalliance/stix-shifter/blob/master/adapter-guide/develop-translation-module.md
instructs the developer to make sure that their stix_translation subdirectory contains data_mapper.py

This appears to be obsolete and should be removed.

**Comment by delliott90** [comment]
Resolved in https://github.com/opencybersecurityalliance/stix-shifter/pull/398
