### ISSUE TITLE
Map Carbon Black Response `last_update` process field to `last_observed`

### ISSUE THREAD

**Issue by crahan** [opencybersecurityalliance/stix-shifter#395]
**Describe the bug**
Missing support for Carbon Black Response `last_update` process fields.

**To Reproduce**
N/A

**Expected behavior**
Currently, the mapping for the `start` field in the Carbon Black Response `to_stix_map.json` translation file is as follows:

```
"start": [
    {
      "key": "process.created",
      "object": "process"
    },
    {
      "key": "first_observed",
      "cybox": false
    },
    {
      "key": "last_observed",
      "cybox": false
    }
  ]
```

However, Carbon Black Response process object provide a `last_update` field that designates when a running process was last updated. This field would map better to `last_observed`.

**Screenshots**
Please see: https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/stix_shifter_modules/carbonblack/stix_translation/json/to_stix_map.json

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Comment by delliott90** [comment]
This would be a good mapping improvement.

**Comment by mdazam1942** [comment]
@crahan is the `last_update` always populated for all process objects after it starts(I assume `start` field will be present for all process events)?

**Comment by crahan** [comment]
That's correct. `last_update` is present on all process data returned from API calls.
