### ISSUE TITLE
Strip out unmapped STIX comparison operators

### ISSUE THREAD

**Issue by mdazam1942** [opencybersecurityalliance/stix-shifter#450]
We currently use the UnmappedAttributeStripper class in stix-shifter to remove comparison statements (from the antlr parsing of the STIX pattern) before translating into a native data source query. This allows us to still construct a query if logically possible (ie. comparison statements joined by OR). We want to do something similar with unmapped operators. Not every data source query language supports the full collection of STIX operators (ie. matches).
 
The operators are defined in a dictionary in each module's query_constructor. They should probably get moved out into a mapping json file for better visibility. We may be able to just add to the attribute stripper logic.

**Comment by delliott90** [comment]
Fixed with https://github.com/opencybersecurityalliance/stix-shifter/pull/744
