### ISSUE TITLE
Move the Flask dependency and proxy host code

### ISSUE THREAD

**Issue by mdazam1942** [opencybersecurityalliance/stix-shifter#452]
Move flask dependency and the proxy host code out of stix-shifter.py to somewhere else. We will add instructions to the developer doc to manually install Flask before running the proxy host.

**Comment by Ryan-Gordon1** [comment]
Hi @mdazam1942 
For this issue are you just looking to have the Flask related code/routes a separate module which stix-shifter uses and same for proxy settings ?

**Comment by yurii-klymenko** [comment]
yes. The idea is to make stix-shifter working without flask dependency installed until it is started in webserver-proxy mode.

**Comment by DerekRushton** [comment]
This is being done with https://github.com/opencybersecurityalliance/stix-shifter/pull/1730. Closing this item.
