### ISSUE TITLE
custom fields dont get checked for null/none

### ISSUE THREAD

**Issue by aviv1ron1** [opencybersecurityalliance/stix-shifter#524]
When translating to stix - fields which dont have any mapping in the "to stix map" json configuration are being mapped to an object named x-<name of the connector>.
So for example if the field `custom` exists in the data source but has no mapping in the "to stix map" of the `qradar` module, it will be mapped to an object named `x-qradar`.
These fields do not get checked for null/none values - unlike the rest of the fields.
This test should be added on these fields - as it creates illegal stix objects since stix does not support null.

steps to reproduce: create an object in the data source which contains a field which does not have any mapping in the "to stix map" json configuration.
Assign `null` as the value of this field.
tranlsate this field to stix.
The resulting stix object will contain a `null` value.

**Comment by delliott90** [comment]
Thanks for catching this.
