### ISSUE TITLE
Governance Process

### ISSUE THREAD

**Issue by sparrell** [opencybersecurityalliance/stix-shifter#537]
**Describe the bug**
The Contributing page does not describe the governance process by which issues are addressed and pull requests are approved. Note the current links are circular (the OCA readme says to look at project readme, the stixshifter readme says to look at contributing, the stixshifter contributing refers to the readme's) and none actually have the governance process

**To Reproduce**
1. Go to https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/CONTRIBUTING.md
2. Nothing on how issues are addressed/closed or how pull requests are accepted

**Expected behavior**
https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/CONTRIBUTING.md updated with either a link to a page describing the governance process or include the text inline on contributing page.

**Additional context**
This was discussed at 4-Feb-2021 OCA PGB. The process exists - it just isn't documented and needs to be. Stixshifter is the most established OCA project and should set a good example for the other projects which are still in startup.

**Comment by DerekRushton** [comment]
Closing due to age. Contributing.md appears to have been removed completely.

**Comment by DerekRushton** [comment]
To be clear, this can be reopened if it's still an issue that needs to be addressed.
