### ISSUE TITLE
Microsoft 365 Defender

### ISSUE THREAD

**Issue by RukhsarRiazKhan** [opencybersecurityalliance/stix-shifter#609]
When are you planning to release a connector for Microsoft 365 Defender EDR?

**Comment by mdazam1942** [comment]
We don't have any Microsoft 365 Defender in our roadmap at the moment. We have connector for Microsoft Advanced Threat Protection(MSATP) currently Microsoft Defender for Endpoint. You can have a look to see if that works for you. 

You can also implement Microsoft 365 Defender connector by following the developer guide https://github.com/opencybersecurityalliance/stix-shifter/blob/master/adapter-guide/develop-stix-adapter.md . If required, we can help you implementing the connector.

**Comment by RukhsarRiazKhan** [comment]
Hi Azam,After checking I found out, that I exactly need "Microsoft Defender for Endpoint" connector. However, on your Github I can see the information about this connector that it "Doesn't work with current version of Microsoft Defender":Can you elaborate?Best regards,Rukhsar KhanInnovative Business Development & Consulting - Threat ManagementGIAC Certified Forensic Analyst (GCFA) Gold-level #12275IBM Security Expert LabsMobile: +49 172 353 0101Email: ***@***.*** God, grant me the serenity to accept the things I cannot change, courage to change the things I can, and wisdom to know the difference.Reinhold Niebuhr-----Md Azam ***@***.***> wrote: -----To: opencybersecurityalliance/stix-shifter ***@***.***>From: Md Azam ***@***.***>Date: 05/10/2021 05:36PMCc: RukhsarRiazKhan ***@***.***>, Author ***@***.***>Subject: [EXTERNAL] Re: [opencybersecurityalliance/stix-shifter] Microsoft 365 Defender (#609)
    
    






 We don't have any Microsoft 365 Defender in our roadmap at the moment. We have connector for Microsoft Advanced Threat Protection(MSATP) currently Microsoft Defender for Endpoint. You can have a look to see if that works for you. You can also



ZjQcmQRYFpfptBannerStart



                    This Message Is From an External Sender
            This message came from outside your organization.
      
    
  

ZjQcmQRYFpfptBannerEnd



We don't have any Microsoft 365 Defender in our roadmap at the moment. We have connector for Microsoft Advanced Threat Protection(MSATP) currently Microsoft Defender for Endpoint. You can have a look to see if that works for you.You can also implement Microsoft 365 Defender connector by following the developer guide https://github.com/opencybersecurityalliance/stix-shifter/blob/master/adapter-guide/develop-stix-adapter.md . If required, we can help you implementing the connector.

**Comment by mdazam1942** [comment]
@RukhsarRiazKhan we have recently updated the connector to support the Microsoft Defender for Endpoint schema and in the process of updating the documentation as well. 
So basically the connector is working in its current state if you want to use it in your application.

**Comment by delliott90** [comment]
Closing this as we now support Microsoft Defender for Endpoint.
