### ISSUE TITLE
Codecov exposure?

### ISSUE THREAD

**Issue by todb-r7** [opencybersecurityalliance/stix-shifter#610]
**Is your feature request related to a problem? Please describe.**
Codecov had a compromise issue you've certainly heard about. I'm wondering if the stix-shifter has ensured they've not had any secrets exposed, and alternatively, if you all have already rotated any exposed secrets.

**Describe the solution you'd like**
I'd love a statement saying that you've done the investigation.

**Additional context**
Just making sure you all are good!

**Comment by mdazam1942** [comment]
We have done the investigation. STIX-Shifter doesn't have any secret exposed. We use github action and codecov-action@v1 for uploading the coverage. We ran `env` in the build to verify and don't see any credentials/token/keys.

**Comment by mdazam1942** [comment]
@todb-r7 we can close this issue if above satisfies your question.

**Comment by todb-r7** [comment]
If you're happy, I'm happy!
