### ISSUE TITLE
Buggy pypi Installation with Python > 3.6

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/stix-shifter#614]
**Describe the bug**
I tested Python 3.9.4, 3.8.10, 3.7.10, and 3.6.13 for directly install packages from pypi. Only the one installed in Python 3.6.13 environment works. This test is done on Fedora 33 with kernel 5.11.18-200.fc33.x86_64. All python versions are official Fedora packages installed via `dnf`.

**To Reproduce**
I setup venv for each Python version I am using for a clean start with only `pip`, `setuptools` and `wheel` installed and up to date.
Then I install stix-shifter with two mature connectors as follows:
```
pip install stix-shifter stix-shifter-utils stix-shifter-modules-qradar stix-shifter-modules-elastic_ecs
```
Then I execute the stix-shifter utility, but failed with the error I cannot trace back with Python 3.7, 3.8, and 3.9:
```
$ stix-shifter translate elastic_ecs query {} "[ipv4-addr:value = '127.0.0.1']" {}
 2021-05-14 15:28:47,354 stix_shifter.stix_translation.stix_translation ERROR    expected str, bytes or os.PathLike object, not NoneType
 2021-05-14 15:28:47,354 stix_shifter.stix_translation.stix_translation ERROR    Caught exception: expected str, bytes or os.PathLike object, not NoneType <class 'TypeError'>
 2021-05-14 15:28:47,360 stix_shifter_utils.stix_translation.stix_translation_error_mapper ERROR    received exception => TypeError: expected str, bytes or os.PathLike object, not NoneType
{
    "success": false,
    "code": "invalid_parameter",
    "error": "Error when converting STIX pattern to data source query: expected str, bytes or os.PathLike object, not NoneType"
}
```
If I clone the repo and execute `python main.py ...`, then it is fine with all Python versions:
```
$ python main.py translate elastic_ecs query {} "[ipv4-addr:value = '127.0.0.1']" {}
 2021-05-14 15:36:56,308 stix_shifter_modules.elastic_ecs.stix_translation.query_translator INFO     Converting STIX2 Pattern to data source query
{
    "queries": [
        "(source.ip : \"127.0.0.1\" OR destination.ip : \"127.0.0.1\" OR client.ip : \"127.0.0.1\" OR server.ip : \"127.0.0.1\" OR host.ip : \"127.0.0.1\" OR dns.resolved_ip : \"127.0.0.1\") AND (@timestamp:[\"2021-05-14T19:31:56.310Z\" TO \"2021-05-14T19:36:56.310Z\"])"
    ]
}
```
I tried the transmission module, and the results are the same.

**Comment by jiyongj** [comment]
I also encountered the same error when using both locally built/installed and pip installed `stix-shifter` with Python v3.7+; and made a pull request to fix one location.
