### ISSUE TITLE
Suggesting move to stix2.1

### ISSUE THREAD

**Issue by highkay** [opencybersecurityalliance/stix-shifter#674]
**Is your feature request related to a problem? Please describe.**
We have built our software on attack-workbench which support stix2.1 only. However stix-shifter has not supported yet. We also  plan to develop a custom translator on our siem later.

**Describe the solution you'd like**
stix-shifter could support stix2.1 inputs and outputs.

**Describe alternatives you've considered**
hack the source code to seperate the `oberservation` manually. It would not be a good idea.

**Additional context**

**Comment by delliott90** [comment]
Thanks for the input. I'm actually working on implementing STIX 2.1 support.

**Comment by alidhamieh** [comment]
Any update on this. I ran execute on a partner and i got the following. It seems to me that is not stix 2.1 yet specifically because of "objects": {
                "0": { IN 
 {
    "type": "bundle",
    "id": "bundle--c9257af0-5315-48f4-9697-20b23d6125c9",
    "spec_version": "2.1",
    "objects": [
        {
            "id": "observed-data--b9ec7340-ecf8-47d6-96a6-7b7a4da5ec9f",
            "type": "observed-data",
            "created_by_ref": "identity--c5856c97-cf65-5abf-85d5-2fb443c51624",
            "created": "2021-11-29T21:08:59.744Z",
            "modified": "2021-11-29T21:08:59.744Z",
            "objects": {
                "0": {
                    "type": "network-traffic",
                    "dst_port": 53,
                    "dst_byte_count": 1100,
                    "dst_ref": "2",
                    "dst_packets": 4,
                    "src_port": 48079,
                    "src_byte_count": 256,
                    "src_ref": "6",
                    "src_packets": 4,
                    "protocols": [
                        "dns",
                        "udp"
                    ]
                }
              
            },
            "first_observed": "2021-11-23T19:07:55.305Z",
            "last_observed": "2021-11-23T19:07:55.305Z",
            "number_observed": 1,
            "nb_deps": 2
        }
    ]
}

**Comment by delliott90** [comment]
Initial 2.1 support has been merged into develop. Try adding `'{"stix_2.1": true}'` to the end of the execute command.

**Comment by alidhamieh** [comment]
@delliott90 I added '{"stix_2.1": true}' to the end and got the below error. Do i need to use different stix-shifter installation for develop version or it is because i put '{"stix_2.1": true}' in the wrong command place. I installed it using the following commands: `pip install stix-shifter; pip install stix-shifter-utils; pip install stix-shifter-modules-elastic-ecs`

Here is the command i executes and the fired up error:
`stix-shifter execute elastic_ecs elastic_ecs '{"type": "identity", "id": "identity--c5456c97-cf65-5abf1624", "name": "Name", "identity_class": "events"}' '{ "host": "test", "port": 9243}' '{"auth":{"username":"elc","password":"xW6uvW"}}'  "[ipv4-addr:value = '192.168.0.159'] START t'2016-06-01T00:00:00Z' STOP t'2021-11-23T20:16:12.779Z'" '{"stix_2.1": true}'`
**usage: stix-shifter [-h] {translate,modules,mapping,transmit,execute,host} ...
stix-shifter: error: unrecognized arguments: {"stix_2.1": true}**

**Comment by alidhamieh** [comment]
I also cloned the stix-shifter dev and generated/installed dependencies and changed default from false to true in ` "stix_2.1": { "type": "boolean", "default": true, "optional": true, "hidden": true}` of `stix-shifter/stix_shifter_modules/config.json` and RAN: 
`sudo python3 main.py execute elastic_ecs elastic_ecs '{"type": "identity", "id": "identity--c5456c97-cf65-5a-85d5-2fb443c51624", "name": "Name", "identity_class": "events"}' '{ "host": "test1-098fc7.eso", "port": 9243}' '{"auth":{"username":"elaic","password":"mW6YsBg3HyPuvW"}}'  "[ipv4-addr:value = '192.168.0.10'] START t'2016-06-01T00:00:00Z' STOP t'2021-11-23T20:16:12.779Z'"`
 2021-11-30 15:20:18,179 stix_shifter_modules.elastic_ecs.stix_translation.query_translator INFO     Converting STIX2 Pattern to data source query
 2021-11-30 15:20:18,267 stix_shifter.scripts.stix_shifter INFO     Translated Queries:
{
    "queries": [
        "(source.ip : \"192.168.0.10\" OR destination.ip : \"192.168.0.10\" OR client.ip : \"192.168.0.10\" OR server.ip : \"192.168.0.10\" OR host.ip : \"192.168.0.10\" OR dns.resolved_ip : \"192.168.0.10\") AND (@timestamp:[\"2016-06-01T00:00:00.000Z\" TO \"2021-11-23T20:16:12.779Z\"])"
    ]
}
 2021-11-30 15:20:18,840 stix_shifter_modules.elastic_ecs.stix_transmission.connector ERROR    Total # of hits:{'value': 589, 'relation': 'eq'}
 2021-11-30 15:20:18,841 stix_shifter_modules.elastic_ecs.stix_transmission.connector ERROR    Total # of records: 9
 2021-11-30 15:20:18,861 requests_cache WARNING  cannot import name 'define'
 2021-11-30 15:20:18,870 stix_shifter_utils.stix_translation.src.json_to_stix.json_to_stix_translator ERROR    STIX object 'autonomous-system' needs at least one of the following properties to generate ID ['number']
 2021-11-30 15:20:18,874 stix_shifter_utils.stix_translation.src.json_to_stix.json_to_stix_translator ERROR    STIX object 'autonomous-system' needs at least one of the following properties to generate ID ['number']
 2021-11-30 15:20:18,875 stix_shifter_utils.stix_translation.src.json_to_stix.json_to_stix_translator ERROR    STIX object 'autonomous-system' needs at least one of the following properties to generate ID ['number']
 2021-11-30 15:20:18,878 stix_shifter_utils.stix_translation.stix_translation_error_mapper ERROR    received exception => RuntimeError: Incorrect number of result objects after translation. Found: 78, expected: 9.
 2021-11-30 15:20:18,879 stix_shifter.scripts.stix_shifter INFO     STIX Results (written to stdout):

{
    "success": false,
    "code": "invalid_parameter",
    "error": "Error when converting STIX pattern to data source query: Incorrect number of result objects after translation. Found: 78, expected: 9."
}

**Comment by mdazam1942** [comment]
@alidhamieh were you able to fix this by updating your develop branch?

**Comment by delliott90** [comment]
Closing this as it's pretty old and STIX 2.1 support is now in stix-shifter as described in https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/OVERVIEW.md#translating-results-into-stix-21
