### ISSUE TITLE
elastic_ecs connector produces SCOs with id property

### ISSUE THREAD

**Issue by pcoccoli** [opencybersecurityalliance/stix-shifter#684]
**Describe the bug**
The result mapping uses things like `x-ecs-user.id` which creates a custom SCO like
```
{
  "id": "0",
  "type": "x-ecs-user"
}
``` 

In STIX 2.0, SCOs should not have an `id` property.  In 2.1, the `id` values the connector produces are invalid.

stix2_validator will reject bundles with such objects as invalid.

**Expected behavior**
These properties should be renamed to something other than `id`.

**Comment by delliott90** [comment]
Fixed in https://github.com/opencybersecurityalliance/stix-shifter/pull/1251
