### ISSUE TITLE
Simplify sync dummy connector translator logic

### ISSUE THREAD

**Issue by mdazam1942** [opencybersecurityalliance/stix-shifter#702]
**Is your feature request related to a problem? Please describe.**
Remove the dictionary: https://github.com/opencybersecurityalliance/stix-shifter/blob/master/stix_shifter_modules/async_dummy/stix_translation/query_constructor.py#L11

And modify the function that uses it.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DerekRushton** [comment]
Closing due to age. The dictionary also appears to have been removed.
