### ISSUE TITLE
stix-shifter's CBCloud module doesn't translate a STIX query

### ISSUE THREAD

**Issue by dganev-cb** [opencybersecurityalliance/stix-shifter#757]
**Describe the bug**
There is a bug in the `translate` function of the cbcloud module of the project. 

**To Reproduce**
Whenever I run:

```console
$ stix-shifter translate cbcloud query {} "[ipv4-addr:value = '127.0.0.1']" {} 
{
    "queries": [
        "(((netconn_ipv4:127.0.0.1 OR netconn_local_ipv4:127.0.0.1)) AND device_timestamp:[2021-12-20T11:46:10Z TO 2021-12-20T11:51:10Z]) AND -enriched:True"
    ]
}
```
It correctly outputs the query, however as soon as I change the IPv4 to anything else than `127.0.0.1`  (eg. `99.48.227.227` which is a legit ipv4 address) it outputs 

```console 
 2021-12-20 13:57:37,874 stix_shifter_modules.cbcloud.stix_translation.query_translator INFO     Converting STIX2 Pattern to Carbon Black Cloud query
 2021-12-20 13:57:37,878 stix_shifter.stix_translation.stix_translation ERROR    Caught exception: local variable 'str_' referenced before assignment <class 'UnboundLocalError'>
 2021-12-20 13:57:37,879 stix_shifter_utils.stix_translation.stix_translation_error_mapper ERROR    received exception => UnboundLocalError: local variable 'str_' referenced before assignment
{
    "success": false,
    "code": "invalid_parameter",
    "error": "Error when converting STIX pattern to data source query: local variable 'str_' referenced before assignment"
}
``` 

**Expected behavior**
A translated query.

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04 (WSL2)

**Smartphone (please complete the following information):**
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0]

**Additional context**
The error is happening here: https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/stix_shifter_modules/cbcloud/stix_translation/query_constructor.py#L134 I believe this is due to the REGEX here: https://github.com/opencybersecurityalliance/stix-shifter/blob/develop/stix_shifter_utils/stix_translation/src/json_to_stix/observable.py#L1 mapping this `99.48.227.227` to a `domain-name` instead of an `IPv4` which then makes the `skip` variable always `True` and we land to a case where the local variable `str_` is not assigned because the `len(comparison_strings)` is always 0. 

I believe the logic for validating an Observable and discovering what type of `value_type` is should be altered. Packages like https://github.com/kvesteri/validators can be used for this sole reason.

**Comment by mdazam1942** [comment]
We are planning to fix this in the module level instead of introducing a new library.

**Comment by dganev-cb** [comment]
> 

Sounds fair!
