### ISSUE TITLE
QRadar module returns many zero ip addresses and mac addresses which are irrelevant

### ISSUE THREAD

**Issue by aviv1ron1** [opencybersecurityalliance/stix-shifter#762]
**Describe the bug**
The QRadar module to stix results contain ip addresses (`0.0.0.0`) and mac addresses (`00:00:00:00:00:00`) which include only zero's.
Since this data is irrelevant it should be filtered out in order to provide more correct results in smaller size.

**To Reproduce**
1. Query for windows event logs thru QRadar
2. When the original log does not contain a source / target mac address or an identity ip these fields will be populated with zero's
3. These get tranlated as stix objects and those get referenced - although they provide no value to the result

**Expected behavior**
I expect that source / destination mac addresses and identity ip's are filtered for zero values since they are not valid values for these, rather they are indicating a null value.

**Comment by DerekRushton** [comment]
In my opinion this is likely working as intended. While inconvenient, we are at the mercy of the API's we communicate with. If the API we are working with returns back 0.0.0.0 and 00:00:00:00:00:00 results than we should interpret them as given. Whether this is relevant or not is up to the user to determine and if it's always irrelevant, than the API should not return it.

That said, if we are inserting these values on our end, this should be changed.

Given the age I am going to close this, however feel free to open this again if it is still relevant.
