### ISSUE TITLE
Wrong start/stop qualifier format doesn't show proper error message in splunk

### ISSUE THREAD

**Issue by mdazam1942** [opencybersecurityalliance/stix-shifter#855]
**Describe the bug**
If wrong timestamp format is specified in the start/stop qualifier for splunk translate command then it doesn't show proper error message.

**To Reproduce**

This splunk translate command:
`stix-shifter translate splunk query {} "[ipv4-addr:value = '10.1.1.1'] START t'2022-03-03T00:00:00Z' STOP t'2022-03-03T01:00:00Z'"`
yields the following error:
```
2022-03-17 08:44:27,593 stix_shifter.stix_translation.stix_translation ERROR Caught exception: Qualifier type not implemented <class 'NotImplementedError'>
2022-03-17 08:44:27,598 stix_shifter_utils.stix_translation.stix_translation_error_mapper ERROR received exception => NotImplementedError: Qualifier type not implemented
{
"success": false,
"code": "not_implemented",
"error": "wrong parameter : Qualifier type not implemented"
}
```
The error doesn't show whether the timestamp format is wrong.
**Expected behavior**

The error should indicate that the timestamp format is wrong.

**Additional context**
In general the\is timestamp should work but this is very specific to splunk. We need to verify why it is required to add `.SSS` in the. qualifier timestamp for splunk.

**Comment by subbyte** [comment]
We also encountered this type of issues in other connectors before, e.g., Elastic_ECS. And we currently have a temperaory patch in Kestrel to pad timestamps to milliseconds. It will be very welcome to support `2022-03-03T00:00:00Z` in STIX-shifter.
https://github.com/opencybersecurityalliance/kestrel-lang/issues/6

**Comment by pcoccoli** [comment]
I think the real bug is that the connector requires milliseconds.  It should accept any number of digits after the decimal, or no decimal at all: https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_ksbm2nost85y
